src/Entity/Question.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 */
class Question
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $name;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"name"})
     */
    private string $slug;

    /**
     * @ORM\Column(type="text")
     */
    private string $question;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $askedAt = null;

    /**
     * @ORM\Column(type="integer")
     */
    private int $votes = 0;

    /**
     * @var Collection|Answer[]
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="question", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private Collection $answers;

    /**
     * @ORM\OneToMany(targetEntity=QuestionTag::class, mappedBy="question")
     */
    private Collection $questionTags;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->questionTags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getAskedAt(): ?DateTimeInterface
    {
        return $this->askedAt;
    }

    public function setAskedAt(?DateTimeInterface $askedAt): self
    {
        $this->askedAt = $askedAt;

        return $this;
    }

    public function getVotesString(): string
    {
        $prefix = $this->getVotes() >= 0 ? '+' : '-';

        return sprintf('%s %d', $prefix, abs($this->getVotes()));
    }

    public function getVotes(): int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function upVote(): self
    {
        ++$this->votes;

        return $this;
    }

    public function downVote(): self
    {
        --$this->votes;

        return $this;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        // set the owning side to null (unless already changed)
        if ($this->answers->removeElement($answer) && $answer->getQuestion() === $this) {
            $answer->setQuestion(null);
        }

        return $this;
    }

    public function getApprovedAnswers(): Collection
    {
        return $this->answers->matching(AnswerRepository::createApprovedCriteria());
    }

    /**
     * @return Collection|QuestionTag[]
     */
    public function getQuestionTags(): Collection
    {
        return $this->questionTags;
    }

    public function addQuestionTag(QuestionTag $questionTag): self
    {
        if (!$this->questionTags->contains($questionTag)) {
            $this->questionTags[] = $questionTag;
            $questionTag->setQuestion($this);
        }

        return $this;
    }

    public function removeQuestionTag(QuestionTag $questionTag): self
    {
        if ($this->questionTags->removeElement($questionTag)) {
            // set the owning side to null (unless already changed)
            if ($questionTag->getQuestion() === $this) {
                $questionTag->setQuestion(null);
            }
        }

        return $this;
    }
}

src/Controller/QuestionController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Question;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class QuestionController extends AbstractController
{
    private LoggerInterface $logger;
    private bool $isDebug;

    public function __construct(LoggerInterface $logger, bool $isDebug)
    {
        $this->logger = $logger;
        $this->isDebug = $isDebug;
    }

    #[Route('/{page<\d+>}', name: 'app_homepage')]
    public function homepage(QuestionRepository $repository, int $page = 1): Response
    {
        $queryBuilder = $repository->createAskedOrderedByNewestQueryBuilder();

        $pagerfanta = new Pagerfanta(new QueryAdapter($queryBuilder));
        $pagerfanta->setMaxPerPage(5);
        $pagerfanta->setCurrentPage($page);

        return $this->render('question/homepage.html.twig', [
            'pager' => $pagerfanta,
        ]);
    }

    /**
     * @Route("/questions/new")
     */
    public function new(): Response
    {
        return new Response('Sounds like a GREAT feature for V2!');
    }

    /**
     * @Route("/questions/{slug}", name="app_question_show")
     */
    public function show(Question $question): Response
    {
        if ($this->isDebug) {
            $this->logger->info('We are in debug mode!');
        }

        return $this->render('question/show.html.twig', [
            'question' => $question,
        ]);
    }

    /**
     * @Route("/questions/{slug}/vote", name="app_question_vote", methods="POST")
     */
    public function questionVote(
        Question $question,
        Request $request,
        EntityManagerInterface $entityManager
    ): \Symfony\Component\HttpFoundation\RedirectResponse {
        $direction = $request->request->get('direction');

        if ('up' === $direction) {
            $question->upVote();
        } elseif ('down' === $direction) {
            $question->downVote();
        }

        $entityManager->flush();

        return $this->redirectToRoute('app_question_show', [
            'slug' => $question->getSlug(),
        ]);
    }
}

templates/question/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="jumbotron-img p-2 mb-2">
    <div class="container">
        <h1 class="display-4">Your Questions Answered</h1>
        <div class="lead">And even answers for those questions you didn't think to ask!</div>
    </div>
</div>
<div class="container">
    <div class="row mb-3">
        <div class="col">
            <button class="btn btn-question">Ask a Question</button>
        </div>
    </div>
    <div class="row">
        {% for question in pager %}
        <div class="col-12 mb-3">
            <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                <div class="q-container p-4">
                    <div class="row">
                        <div class="col-2 text-center">
                            <img src="{{ asset('images/tisha.png') }}" width="100" height="100"  alt="Tisha avatar">
                            <div class="vote-arrows vote-arrows-alt flex-fill pt-2" style="min-width: 90px;">
                                <span>{{ question.votesString}} votes</span>
                            </div>
                            {% for questionTag in question.questionTags %}
                                <span class="badge rounded-pill bg-light text-dark">{{ questionTag.tag.name }}</span>
                            {% endfor %}
                        </div>
                        <div class="col">
                            <a class="q-title" href="{{ path('app_question_show', { slug: question.slug }) }}"><h2>{{ question.name }}</h2></a>
                            <div class="q-display p-3">
                                <i class="fa fa-quote-left mr-3"></i>
                                <p class="d-inline">{{ question.question|parse_markdown }}</p>
                                <p class="pt-4"><strong>--Tisha</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="answer-link" href="{{ path('app_question_show', { slug: question.slug }) }}" style="color: #fff;">
                    <p class="q-display-response text-center p-3">
                        <i class="fa fa-magic magic-wand"></i> {{ question.approvedAnswers|length}} answers
                    </p>
                </a>
            </div>
        </div>
        {% endfor %}
        {{ pagerfanta(pager) }}
    </div>
</div>
{% endblock %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question: {{ question.name }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="my-4">Question:</h2>
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="q-container-show p-4">
                        <div class="row">
                            <div class="col-2 text-center">
                                <img src="{{ asset('images/tisha.png') }}" width="100" height="100" alt="Tisha avatar">
                                <div class="mt-3">
                                    <small>
                                        {% if question.askedAt %}
                                            Asked <br>
                                            {{ question.askedAt|ago }}
                                        {% else %}
                                            (unpublished)
                                        {% endif %}
                                    </small>

                                    <form action="{{ path('app_question_vote', { slug: question.slug }) }}"
                                          method="POST">
                                        <div class="vote-arrows vote-arrows-alt flex-fill pt-2"
                                             style="min-width: 90px;">
                                            <button class="vote-up btn btn-link" name="direction" value="up"><i
                                                        class="far fa-arrow-alt-circle-up"></i></button>
                                            <button class="vote-down btn btn-link" name="direction" value="down"><i
                                                        class="far fa-arrow-alt-circle-down"></i></button>
                                            <span>{{ question.votesString }}</span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col">
                                <h1 class="q-title-show">{{ question.name }}</h1>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left mr-3"></i>
                                    <p class="d-inline">{{ question.question|parse_markdown }}</p>
                                    <p class="pt-4"><strong>--Tisha</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-between my-4">
            <h2 class="">Answers <span style="font-size:1.2rem;">({{ question.approvedAnswers|length }})</span></h2>
            <button class="btn btn-sm btn-secondary">Submit an Answer</button>
        </div>

        <ul class="list-unstyled">
            {% for answer in question.approvedAnswers %}
                {{ include('answer/_answer.html.twig') }}
            {% endfor %}
        </ul>
    </div>
{% endblock %}